### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by ctibo** [blockshake-io/defly-connect#16]
## Issue
I noticed that the modal is trying to load a missing font (`/asset/fonts/pp-right-grotesk-wide-black.woff2`). This font is used on the modal title. 

![image](https://github.com/blockshake-io/defly-connect/assets/5271371/c36bf3bf-cc1a-4476-97bf-5f7f8b2dbbf0)

The font files can be found in the `src` folder of the npm package, but they don't seem to be bundled in the `dist` folder. I could set my project bundler to resolve and copy those files in my project asset folder, but I think a proper license file would be required to make sure the distribution of this font is legitimate.
  

 ## Possible fixes
 
**Option 1**
Load the font from a CDN where you can actually track font usage and pay for the appropriate license. 
Providing the font license file in the repository would also be a good thing. 

**Option 2**
Provide code samples on how to copy assets with different bundlers (webpack, vitejs, rollup). 
I think a proper license for font distribution would be required.
 
**Option 3** (the quick fix)
Replace the font with a similar Google font loaded from their CDN. 
You are already doing this with the "Spline Sans", and it seems to work perfectly.

**Comment by k13n** [comment]
Thanks! This is addressed in PR #17. We will deploy a new version of Defly Connect.

**Comment by k13n** [comment]
We just released Defly Connect v1.1.6, please let us know if you still have any problems!
