### ISSUE TITLE
Can't send ALGO or ASAs to newly minted NFD

### ISSUE THREAD

**Issue by adamparish** [blockshake-io/defly-connect#19]
**Expected Result**
As a Defly user, I should be able to type "newlyminted.algo" in the "To address" field so that I can easily send ALGO or ASA to another Aglroand account.

**Actual Result**
As a Defly User, when I type "newlyminted.algo" in the "To Address" field for a newly minted NFD, I receive the following error. "Invalid destination address"

Steps to reproduce:
1. Launch Defly on Android
2. Touch send CTA on homescreen
3. Input a quantity to send
4. Select ALGO or an ASA
5. type "newlyminted.algo" into the To address
6. Tap send button

_Please note that I haven't tested this on iOS._ Tested today on Defly App for Android v1.5.9 (Build 270) Also, I can send to older NFDs. I just can't send to newly minted NFD.

**Comment by adamparish** [comment]
Maybe this Defly server-side caching related?

**Comment by k13n** [comment]
I'm closing this issue now as the Defly release that fixes this bug is being rolled out to everyone. Thanks a lot for reporting!
