### ISSUE TITLE
DeflyWalletConnectError: invalid transaction group

### ISSUE THREAD

**Issue by bigbulb** [blockshake-io/defly-connect#21]
Hello,

I am working on a Dapp in Typescript and when trying to send a group of 3 transactions to Defly, I am facing the following issue:

_DeflyWalletConnectError: invalid transaction group_

On my Dapp, I tried connecting with Pera and sending the exact same transactions and no issue (when signing multiple transaction with Pera, I don't group them as it yields an error).
With Defly, whether I group them or not, I am still getting the same error. Is there anything that I am missing? Does Defly support atomic transactions?

**Comment by k13n** [comment]
Interesting! This sounds like your transaction group doesn't pass our ARC-1 (https://arc.algorand.foundation/ARCs/arc-0001) validation. This either means there's a bug in our ARC-1 implementation or your transaction group doesn't adhere to ARC-1. In either case it'd be interesting to see the transaction group that you're building. Could you share it?

**Comment by bigbulb** [comment]
Please see below. Those are just 2 transactions. Hope it is readable!

`[
    {
        "txn": {
            "name": "Transaction",
            "tag": {
                "type": "Buffer",
                "data": [
                    84,
                    88
                ]
            },
            "genesisID": "mainnet-v1.0",
            "genesisHash": {
                "type": "Buffer",
                "data": [
                    192,
                    97,
                    196,
                    216,
                    252,
                    29,
                    189,
                    222,
                    210,
                    215,
                    96,
                    75,
                    228,
                    86,
                    142,
                    63,
                    109,
                    4,
                    25,
                    135,
                    172,
                    55,
                    189,
                    228,
                    182,
                    32,
                    181,
                    171,
                    57,
                    36,
                    138,
                    223
                ]
            },
            "type": "axfer",
            "fee": 1000,
            "firstRound": 36828331,
            "lastRound": 36829331,
            "note": {
                "0": 111,
                "1": 112,
                "2": 116,
                "3": 32,
                "4": 105,
                "5": 110,
                "6": 116,
                "7": 111,
                "8": 32,
                "9": 116,
                "10": 101,
                "11": 97,
                "12": 109,
                "13": 32,
                "14": 97,
                "15": 115,
                "16": 115,
                "17": 101,
                "18": 116
            },
            "lease": {},
            "from": {
                "publicKey": {
                    "0": 63,
                    "1": 233,
                    "2": 73,
                    "3": 222,
                    "4": 144,
                    "5": 228,
                    "6": 177,
                    "7": 169,
                    "8": 75,
                    "9": 238,
                    "10": 197,
                    "11": 228,
                    "12": 237,
                    "13": 126,
                    "14": 40,
                    "15": 76,
                    "16": 172,
                    "17": 68,
                    "18": 1,
                    "19": 49,
                    "20": 180,
                    "21": 217,
                    "22": 241,
                    "23": 214,
                    "24": 151,
                    "25": 218,
                    "26": 91,
                    "27": 55,
                    "28": 183,
                    "29": 107,
                    "30": 123,
                    "31": 18
                },
                "checksum": {
                    "0": 222,
                    "1": 134,
                    "2": 124,
                    "3": 219
                }
            },
            "group": {
                "type": "Buffer",
                "data": [
                    122,
                    107,
                    77,
                    121,
                    39,
                    90,
                    33,
                    183,
                    157,
                    140,
                    204,
                    34,
                    234,
                    132,
                    142,
                    175,
                    10,
                    224,
                    26,
                    244,
                    92,
                    55,
                    172,
                    128,
                    160,
                    175,
                    84,
                    185,
                    39,
                    100,
                    139,
                    61
                ]
            },
            "assetIndex": 598372317,
            "to": {
                "publicKey": {
                    "0": 63,
                    "1": 233,
                    "2": 73,
                    "3": 222,
                    "4": 144,
                    "5": 228,
                    "6": 177,
                    "7": 169,
                    "8": 75,
                    "9": 238,
                    "10": 197,
                    "11": 228,
                    "12": 237,
                    "13": 126,
                    "14": 40,
                    "15": 76,
                    "16": 172,
                    "17": 68,
                    "18": 1,
                    "19": 49,
                    "20": 180,
                    "21": 217,
                    "22": 241,
                    "23": 214,
                    "24": 151,
                    "25": 218,
                    "26": 91,
                    "27": 55,
                    "28": 183,
                    "29": 107,
                    "30": 123,
                    "31": 18
                },
                "checksum": {
                    "0": 222,
                    "1": 134,
                    "2": 124,
                    "3": 219
                }
            }
        },
        "signers": [
            "?�Iސ䱩K����~(L�D\u00011���֗�[7�k{\u0012"
        ]
    },
    {
        "txn": {
            "name": "Transaction",
            "tag": {
                "type": "Buffer",
                "data": [
                    84,
                    88
                ]
            },
            "genesisID": "mainnet-v1.0",
            "genesisHash": {
                "type": "Buffer",
                "data": [
                    192,
                    97,
                    196,
                    216,
                    252,
                    29,
                    189,
                    222,
                    210,
                    215,
                    96,
                    75,
                    228,
                    86,
                    142,
                    63,
                    109,
                    4,
                    25,
                    135,
                    172,
                    55,
                    189,
                    228,
                    182,
                    32,
                    181,
                    171,
                    57,
                    36,
                    138,
                    223
                ]
            },
            "type": "axfer",
            "fee": 1000,
            "firstRound": 36828331,
            "lastRound": 36829331,
            "note": {
                "0": 66,
                "1": 108,
                "2": 111,
                "3": 99,
                "4": 107,
                "5": 32,
                "6": 116,
                "7": 101,
                "8": 97,
                "9": 109,
                "10": 32,
                "11": 102,
                "12": 101,
                "13": 101,
                "14": 46
            },
            "lease": {},
            "from": {
                "publicKey": {
                    "0": 63,
                    "1": 233,
                    "2": 73,
                    "3": 222,
                    "4": 144,
                    "5": 228,
                    "6": 177,
                    "7": 169,
                    "8": 75,
                    "9": 238,
                    "10": 197,
                    "11": 228,
                    "12": 237,
                    "13": 126,
                    "14": 40,
                    "15": 76,
                    "16": 172,
                    "17": 68,
                    "18": 1,
                    "19": 49,
                    "20": 180,
                    "21": 217,
                    "22": 241,
                    "23": 214,
                    "24": 151,
                    "25": 218,
                    "26": 91,
                    "27": 55,
                    "28": 183,
                    "29": 107,
                    "30": 123,
                    "31": 18
                },
                "checksum": {
                    "0": 222,
                    "1": 134,
                    "2": 124,
                    "3": 219
                }
            },
            "group": {
                "type": "Buffer",
                "data": [
                    122,
                    107,
                    77,
                    121,
                    39,
                    90,
                    33,
                    183,
                    157,
                    140,
                    204,
                    34,
                    234,
                    132,
                    142,
                    175,
                    10,
                    224,
                    26,
                    244,
                    92,
                    55,
                    172,
                    128,
                    160,
                    175,
                    84,
                    185,
                    39,
                    100,
                    139,
                    61
                ]
            },
            "assetIndex": 251014570,
            "amount": 16,
            "to": {
                "publicKey": {
                    "0": 196,
                    "1": 8,
                    "2": 98,
                    "3": 210,
                    "4": 237,
                    "5": 181,
                    "6": 188,
                    "7": 146,
                    "8": 226,
                    "9": 58,
                    "10": 126,
                    "11": 229,
                    "12": 62,
                    "13": 169,
                    "14": 174,
                    "15": 252,
                    "16": 126,
                    "17": 59,
                    "18": 5,
                    "19": 105,
                    "20": 153,
                    "21": 225,
                    "22": 247,
                    "23": 45,
                    "24": 149,
                    "25": 189,
                    "26": 172,
                    "27": 26,
                    "28": 96,
                    "29": 71,
                    "30": 194,
                    "31": 24
                },
                "checksum": {
                    "0": 200,
                    "1": 9,
                    "2": 240,
                    "3": 15
                }
            }
        },
        "signers": [
            "?�Iސ䱩K����~(L�D\u00011���֗�[7�k{\u0012"
        ]
    }
]`

**Comment by k13n** [comment]
From this it's a bit hard to reconstruct the actual transactions. Is there a way you could get the canonical msgpack encoding and send it to me?

Also, in your initial message you mentioned that your transaction group has three transactions, but in this file there are only two transactions.

**Comment by bigbulb** [comment]
Resolved, thank you!
