### ISSUE TITLE
Bump Algosdk

### ISSUE THREAD

**Issue by barnjamin** [blockshake-io/defly-connect#8]
An older peer dependency can be updated to 2.1.0 which has some fixes for the buffer issues folks had

https://github.com/blockshake-io/defly-connect/blob/main/package.json#L41

latest release
https://github.com/algorand/js-algorand-sdk/releases/tag/v2.1.0

**Comment by hanmit** [comment]
Thanks, we will release a new version with algosdk 2.1.0 soon!

**Comment by hanmit** [comment]
The new version 1.1.2 has been released, so I'm closing this issue.
